#!/bin/bash
source env-prep
enable=${1:-"all"} #or none
PERSIST=${PERSIST:-"transient"}
oc exec -n $LOGGING_NS -c elasticsearch $pod -- es_util --query=_cluster/settings -XPUT -d "{\"${PERSIST}\":{\"cluster.routing.allocation.enable\":\"${enable}\"}}"
