#!/bin/bash

cd $(dirname "${BASH_SOURCE[0]}")
source env-prep

index=${1}
shard=${2:-0}
primary=${3:-'false'}

oc -n $LOGGING_NS exec -c elasticsearch $pod -- es_util --query=_cluster/allocation/explain?pretty -d"{\"index\": \"$index\", \"shard\": $shard, \"primary\": $primary}"
