#!/bin/bash

cd $(dirname "${BASH_SOURCE[0]}")
cd $(dirname "${BASH_SOURCE[0]}")
source env-prep

echo "node                                        instance type"
for n in $(oc get nodes -l node-role.kubernetes.io/infra=true -o jsonpath={.items[*].metadata.name}); do
  instance_type=$(oc get node $n -o jsonpath={.metadata.labels.beta\\.kubernetes\\.io/instance-type})
  echo "$n  $instance_type"
done
