#!/bin/bash

cd $(dirname "${BASH_SOURCE[0]}")
source env-prep
echo "Deployments"
echo "----"
oc get deployments -n $LOGGING_NS -o yaml | grep image: | sort | uniq

echo "Daemonsets"
echo "----"
oc get ds -n $LOGGING_NS -o yaml | grep image: | sort | uniq

echo "Cronjobs"
echo "----"
oc get cronjobs -n $LOGGING_NS -o yaml | grep image: | sort | uniq

echo "Pods"
echo "----"
for p in $(oc get pods -n $LOGGING_NS -o jsonpath={.items[*].metadata.name}); do
    echo "$p : $(oc get pod $p -n $LOGGING_NS -o yaml | grep image: | sort | uniq)"
done

