#!/bin/bash -e

cd $(dirname "${BASH_SOURCE[0]}")
source env-prep

component=$1
component=${component:-}

if [ -n "$component" ] ; then
  component="-l component=${component}"
fi

oc -n ${LOGGING_NS} get pods ${component:-}
