#!/usr/bin/bash
# This script displays the current set of SearchGuard permissions
#
# must have access to logging project.  The inputs are:
#   pod   An Elasticsearch pod name

source env-prep

roles=$(oc exec -c elasticsearch $pod -- es_acl get --doc=roles)
mappings=$(oc exec -c elasticsearch $pod -- es_acl get --doc=rolesmapping)
actions=$(oc exec -c elasticsearch $pod -- es_acl get --doc=actiongroups)

read -r -d '' SCRIPT << "EOF"
import json,sets,sys

roles=json.loads(sys.argv[1])
mappings=json.loads(sys.argv[2])
actions=json.loads(sys.argv[3])

def permissions(name,perms=sets.Set()):
  if name in actions:
      for a in actions[name]:
          if a in actions and a not in perms:
            perms.union(permissions(a,perms))
          else:
            perms.add(a)
      return perms
  perms.add(name)
  return perms

def printPermissions(perms):
  for perm in perms:
    roleActions = sets.Set()
    permissions(perm, roleActions)
    for action in sorted(roleActions):
        print "        |-" + action

for role in mappings:
    for mtype, users in mappings[role].iteritems():
       if 'users' == mtype:
         for user in users:
             print ""
             print user
             if role in roles:
               perms = roles[role]
               for ptype, pset in perms.iteritems():
                   if 'cluster' == ptype:
                       print "  |--- cluster:"
                       printPermissions(pset)
                   if 'indices' == ptype:
                       print "  |- indices:"
                       for index, docperms in pset.iteritems():
                           for doc, perms in docperms.iteritems():
                               print "    |-" + index + "/" + doc
                               printPermissions(perms)
             else:
                 print "[WARN] role not found for rolemapping:" + role

EOF

python -c "$SCRIPT" "$roles" "$mappings" "$actions"

